repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: requirements-txt-fixer
    -   repo: https://github.com/pre-commit/mirrors-prettier
        rev: v3.0.3
        hooks:
        -   id: prettier
            files: \.(json|yml)$
    -   repo: https://github.com/dnephin/pre-commit-golang
        rev: v0.5.1
        hooks:
        -   id: go-fmt
        -   id: go-vet
            args: [./...]
            entry: go vet
            language: system
            types: [go]
            pass_filenames: false
        -   id: go-lint
        -   id: go-imports
        -   id: go-cyclo
            args: [-over=15]
        -   id: validate-toml
        -   id: no-go-testing
        -   id: golangci-lint
            args: [--timeout=5m]
        -   id: go-critic
        -   id: go-unit-tests
        -   id: go-build
        -   id: go-mod-tidy
